server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: amigoscode
#    usually this would be a different postgres instance
    url: jdbc:postgresql://localhost:5433/fraud
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true